### PR TITLE
switch AWS::CLI::Config::Profile to Class::Tiny, for easier subclassing

### PR DESCRIPTION
**Pull request by karenetheridge**
Class::Tiny supports BUILD, BUILDARGS etc, so it's possible to subclass
with a Moo or Moose class.

### CODE REVIEW

**Comment by jjatria** [comment]
Thanks for the contribution!

I recently adopted this module (at least partially), and I was planning on pushing [these changes](https://github.com/jjatria/perl5-AWS-CLI-Config/blob/devel/lib/AWS/CLI/Config.pm#L156-L184) to the definition of the `Profile` class. But they go in the opposite direction, by removing Object::Tiny entirely (and instead relying on `AUTOLOAD`).

From the way the distribution is structured, it seemed to me that the class would be mostly for internal use, so subclassing didn't seem so important. I was basically considering it little more than a convenience package to be able to access the fields in the config without the curly braces (hence the use of `AUTOLOAD`, since it's not clear what fields would be defined for the profile). But I'm open to the possibility that this is a terrible decision.

What do you think?

**Comment by karenetheridge** [comment]
As I am in the process of excising Object::Tiny from my $work's codebase, I am more strongly interested in a move *from* OT than *to* CT. However, AUTOLOAD has some thorny edges (plus adding a performance penalty)... the sorts of things that Class::Tiny has taken time to think about (and test), so...  :)

**Comment by jjatria** [comment]
As far as I understood things, the way I'm using AUTOLOAD would basically just have that penalty the first time a given method is called, and for all later calls it would just use an installed method (skipping AUTOLOAD altogether). But please correct me if I'm wrong.

The reason I thought about using it is that if you have a profile that defines eg. an `s3` field (like [here](https://github.com/key-amb/perl5-AWS-CLI-Config/blob/master/t/04_config.t#L17-L22)), it's not very intuitive that you can call `$profile->aws_access_key_id` but have to call `$profile->{s3}`. Can you think of a cleaner way to address this?

**Comment by jjatria** [comment]
The dependency on Object::Tiny was removed in 0.05 using the AUTOLOAD approach.

But I'm still open to being convinced Class::Tiny is a better alternative!

Closing this for now.

**Pull request closed without merging**
